spring:
  datasource:
    url: jdbc:postgresql://test.elegant-designs.net:5432/shervin
    username: shervin
    password: shervin
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://test.elegant-designs.net:8761/eureka
server:
  port: 8081
app:
  email:
    password: Asd123!@
