spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shervin
    username: postgres
    password: postgres
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
app:
  email:
    password: Asd123!@
